### PR TITLE
Fix valuation from discoid

### PR DESCRIPTION
**Pull request by swewers**
Some improvements to the code for creating valuations corresponding to discoids.

### CODE REVIEW

**Comment by swewers** [comment]
The test failure in coverage seems to be an import problem. 
I have the same problem when testing on my computer. When I do (in Sage)

sage: import 'module'
sage: run_doctest('module')

all tests pass. But when I do sage -t <module>, I have the same import problems as above.

**Comment by saraedum** [comment]
In Python 2 there is no default encoding for files. (In Python 3 it's UTF-8.) The coverage tests run with Python 2 and so Python does not know how to handle non-ASCII characters such as the one that is meant to say `…`. Adding an explicit encoding to all files fixes this I think. I'll do so in another PR.

**Comment by swewers** [comment]
How can I reactivate the tests for this pull request?

Or should I first merge this branch with the new master branch?

**Comment by saraedum** [comment]
You need to merge in the master branch to make the tests run again with my changes.

**Comment by swewers** [comment]
Thanks, now everything works.

**Pull request merged**
