### PR TITLE
Add a test case/benchmark

### LINKED ISSUE #61: Valuation does not approximate a unique extension of Valuation on rational function field
The following bug was found ba Jan Steffen Müller (thanks!):

    K = QQ
    FX.<x> = FunctionField(K)
    R.<T> = FX[]
    f = 64*x^3*T - 64*x^3 + 36*x^2*T^2 + 208*x^2*T + 192*x^2 + 9*x*T^3 + 72*x*T^2 + 240*x*T + 64*x +T^4 + 9*T^3 + 52*T^2 + 48*T 
    FY.<y> = FX.extension(f)
    Y = SmoothProjectiveCurve(FY)
    vp = QQ.valuation(13)
    YYp = SemistableModel(Y, vp)
    YYp.is_semistable()

    ValueError                                Traceback (most recent call last)
    ...
    ValueError: The valuation [ Gauss valuation induced by Valuation on rational function field induced by [ Gauss valuation induced by 13-adic valuation, v(x + 10) = 2/7 ], v(y + 9*x + 97) = 4/7 ] does not approximate a unique extension of Valuation on rational function field induced by [ Gauss valuation induced by 13-adic valuation, v(x + 10) = 2/7 ] with respect to y^4 + (9*x + 9)*y^3 + (36*x^2 + 72*x + 52)*y^2 + (64*x^3 + 208*x^2 + 240*x + 48)*y - 64*x^3 + 192*x^2 + 64*x

I know how to fix it, and I will upload a fix in a minute.

### PR DESCRIPTION
**Pull request by saraedum**
the case reported in #61. Fixes #61.

### CODE REVIEW

**Comment by saraedum** [comment]
@swewers: Does this curve have an actual name?

**Comment by swewers** [comment]
The curve is the "exceptional modular curve associated to S_4".

**Comment by swewers** [comment]
How can I change the current version of this pull request myself?
If I knew how to do this I would add the name of the curve in the benchmark and merge.

**Comment by saraedum** [comment]
Since you're a maintainer of this repository, you should be able to just click on the edit icon in the "Files changed" tab here on github.

**Comment by saraedum** [comment]
I think you would have to add my repository as a remote:
```
git remote add saraedum git@github.com:saraedum/mclf.git
```
Then you should be able to push and pull to the branch here with:
```
git fetch saraedum
git checkout bench61
...
git push saraedum
```
But I haven't tried.

**Pull request merged**
